CREATE TABLE XBONUS
(
	MEMBERID BIGINT NOT NULL,
	BONUSPOINT INTEGER NOT NULL,
	OPTCOUNTER SMALLINT NOT NULL,
	CONSTRAINT P_XBONUS PRIMARY KEY (MEMBERID),
	CONSTRAINT F_XBONUS FOREIGN KEY (MEMBERID) REFERENCES USERS (USERS_ID) ON DELETE CASCADE
);