CREATE TABLE XBONUS (
		MEMBERID BIGINT NOT NULL,
		BONUSPOINT INTEGER NOT NULL,
		OPTCOUNTER SMALLINT NOT NULL
	)
	DATA CAPTURE NONE ;
ALTER TABLE XBONUS ADD CONSTRAINT XBONUS_PK PRIMARY KEY
	(MEMBERID);
